[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "cd delivery_system",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "cd delivery_system && python3 -m uvicorn unified_app:app --host 0.0.0.0 --port $PORT"
