[phases.setup]
nixPkgs = ["python312", "gcc", "libffi"]

[phases.install]
cmds = [
  "cd delivery_system && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd delivery_system && uvicorn unified_app:app --host 0.0.0.0 --port $PORT"
