services:
  # Banco de dados PostgreSQL compartilhado
  - type: pserv
    name: entrega-db
    env: docker
    plan: starter
    ipAllowList: []
    
  - type: web
    name: entrega-web
    env: docker
    rootDir: delivery_system
    dockerfilePath: ./Dockerfile.web
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
      - key: BOT_USERNAME
        sync: false
      - key: BASE_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: entrega-db
          property: connectionString
    healthCheckPath: /health
    plan: standard
    
  - type: worker
    name: entrega-bot
    env: docker
    rootDir: delivery_system
    dockerfilePath: ./Dockerfile.bot
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: BASE_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: entrega-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
    plan: standard
